name: run-tests
on:
  push:
    branches: [master]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Install packages'
        run: npm install
      - name: Run linter
        run: npm run lint
  E2E-Test-Cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Install packages'
        run: npm install
      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev:host
  Unit-Test-vitest:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: 'Install packages'
        run: npm install
      - name: Run unit tests
        run: npm run test:unit