name: run-tests
on:
  push:
    branches: [master]

jobs:
  E2E-Test-Cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Installs packages'
        run: npm install
      - uses: cypress-io/github-action@v6
        with:
          start: npm run dev:host
  Unit-Test-vitest:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with: 
          node-version: "20.x"
      - name: Install jest
        run: npm install --save-dev jest
      - name: Run tests
        run: npm run test 